services:
  mtt-redis:
    container_name: mtt-redis
    hostname: mtt-redis
    image: library/redis:7-alpine
    init: true
    networks:
      - mtt-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  mtt-mysql:
    container_name: mtt-mysql
    hostname: mtt-mysql
    image: mariadb
#    init: true
    networks:
      - mtt-network
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 7310:3306
#    volumes:
#      - mtt-mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  mtt-app:
    container_name: mtt-app
    build:
      dockerfile: ${PWD}/deploy/php/loc.Dockerfile
      context: ${PWD}/
    hostname: mtt-app
    networks:
      - mtt-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mtt-mysql:
        condition: service_healthy
      mtt-redis:
        condition: service_healthy
    env_file:
      - .env
#      - local.env
    command: [ "/usr/local/bin/entrypoint.sh"]
    volumes:
      - ${PWD}/:/var/www

  mtt-app-worker:
    container_name: mtt-app-worker
    build:
      dockerfile: ${PWD}/deploy/php/loc.Dockerfile
      context: ${PWD}/
    restart: always
    hostname: mtt-app-worker
    networks:
      - mtt-network
    depends_on:
      mtt-mysql:
        condition: service_healthy
      mtt-redis:
        condition: service_healthy
      mtt-reverb:
        condition: service_started
    env_file:
      - .env
    command: [ "php", "/var/www/artisan", "queue:work", "--queue=default,import"]
    volumes:
      - ${PWD}/:/var/www

  mtt-app-nginx:
     image: nginx
     container_name: mtt-app-nginx
     init: true
     networks:
       - mtt-network
     hostname: ${HOST}
     links:
       - mtt-app
     depends_on:
       - mtt-app
     ports:
       - 80:80
     volumes:
       - ${PWD}/deploy/nginx/templates:/etc/nginx/templates
       - ${PWD}/public:/var/www/public
     environment:
       VIRTUAL_HOST: ${HOST}
       NGINX_BACKEND_HOST: mtt-app
       NGINX_SERVER_ROOT: /var/www/public

  mtt-reverb:
    build:
      dockerfile: ${PWD}/deploy/php/loc.Dockerfile
      context: ${PWD}/
    restart: always
    hostname: localhost
    env_file:
      - .env
    environment:
      LOG_CHANNEL: stdout
#    command: [ "php", "/var/www/artisan", "reverb:start", "--port=18080"]
    command: [ "/usr/local/bin/node-entrypoint.sh"]
    stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
    ports:
      - "18080:18080"
    networks:
      - mtt-network
    volumes:
      - ${PWD}/:/var/www

networks:
  mtt-network:
    name: mtt-network

volumes:
  mtt-mysql-data:
  mtt-rabbitmq:
